#!/usr/bin/env bash

# set -x

LOCATIONS="$HOME/Alexandria $HOME/Documents $HOME/Downloads"

FILES=$(find $LOCATIONS -type f -name "*.pdf")

SELECTED=$(echo "$FILES" | fzf -m)

if [ -n "$SELECTED" ]; then
  while IFS= read -r file; do
    nohup zathura "$file" > /dev/null 2>&1 &
  done <<< "$SELECTED"
fi
