#!/usr/bin/env fish

set -l base_targets "$HOME/Developer/Projects"

set -l all_directories "$HOME/Notes" "$HOME/Developer" "$HOME/Developer/Projects" "$HOME/Developer/Playground"
set -l all_directories $all_directories (find $base_targets -mindepth 1 -maxdepth 2 -type d)

set selected (echo $all_directories | tr ' ' '\n' | fzf-tmux -p)

if test -z $selected
  return 0
end

set selected_name (basename $selected | tr . _)

tmux new-session -ds $selected_name -c $selected &>>/dev/null
tmux switch-client -t $selected_name &>>/dev/null
