# Colors (Gruvbox Material Hard Light)

# Default colors
[colors.primary]
background = "#F9F5D7"
foreground = "#654735"

# Normal colors
[colors.normal]
black   = "#654735"
red     = "#C14A4A"
green   = "#6C782E"
yellow  = "#B47109"
blue    = "#45707A"
magenta = "#945E80"
cyan    = "#4C7A5D"
white   = "#F2E5BC"

# Bright colors (same as normal colors)
[colors.bright]
black   = "#654735"
red     = "#C14A4A"
green   = "#6C782E"
yellow  = "#B47109"
blue    = "#45707A"
magenta = "#945E80"
cyan    = "#4C7A5D"
white   = "#F2E5BC"
