#!/usr/bin/env bash

md2tex() {
    pandoc \
        --standalone \
        -f markdown-implicit_figures \
        -t latex \
        "$1" \
        -o $(echo "$1" | sed "s/.md$/.tex/")
}

main() {
    for file in "$@"; do
        # Pictures in markdown cannot be fetched if
        # we are not in the same directory.
        cd $(dirname $(fullpath "$file"))
        md2tex $(basename "$file")
        cd -
    done
}

main $@
