# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on = ["<C-n>"]
run = '''
shell 'dragon-drop -x -i -A -T "$@"' --confirm
'''

[[manager.prepend_keymap]]
on = ["y"]
run = ["yank", '''
shell --confirm 'echo "$@" | xclip -i -selection clipboard -t text/uri-list'
''']

[[manager.prepend_keymap]]
on = ["<->"]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[input.prepend_keymap]]
on = ["<Esc>"]
run = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on = ["b", "g"]
run = '''
shell 'cp "$0" ~/.config/i3/backgrounds/wall.jpg && feh --bg-fill "$0" && betterlockscreen -u "$0" --fx' --confirm
'''
desc = "Set current image as the background."

[[manager.prepend_keymap]]
on = ["c", "z"]
run = """
shell '$HOME/.config/yazi/scripts/zip.sh "$@"' --block --confirm
"""
desc = "Compress selected files into a single ZIP."

[[manager.prepend_keymap]]
on = ["k"]
run = "plugin --sync arrow --args=-1"

[[manager.prepend_keymap]]
on = ["j"]
run = "plugin --sync arrow --args=1"

[[manager.prepend_keymap]]
on = ["K"]
run = "plugin --sync parent-arrow --args=-1"

[[manager.prepend_keymap]]
on = ["J"]
run = "plugin --sync parent-arrow --args=1"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = ["T"]
run = "plugin --sync hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on = ["M"]
run = "plugin --sync max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on = ["f"]
run = "plugin jump-to-char"
desc = "Jump to char"
